ALTER TABLE app_users ADD COLUMN image VARCHAR(500);
ALTER TABLE app_users ADD COLUMN gender VARCHAR(30);
ALTER TABLE app_users ADD COLUMN birth_date DATE;
ALTER TABLE app_users ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE app_users ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
